### ISSUE TITLE
WMO_INST_TYPE

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#17]
@Annie wong queried whether WMO_INST_TYPE should be filled by the platform maker, or whether it should be left to the DAC.

I assume that usually this is fixed when the float leaves the platform maker, so it makes sense for the platform maker to describe what float they have assembled. Does the owner ever reconfigure the float such that this might change ? UW obviously assembles APEX floats and decides on the sensor configuration. We'll need to ensure our schemas can completely capture the pathway for UW APEXs. Likewise if LOV modifies a PROVOR sensor payload.

But generally I would think the platform maker is well placed to fill this field.

Comments welcome

**Comment by SBS-EREHM** [comment]
The Argo User manual indicates **mandatory** parameters below (In the Argo User's Manual, see **2.4.9 Mandatory metadata parameters**)

.So, I decided to make them mandatory  i the platform schema.so that either the platform maker (e.g., SBS) or the customer/integrator has to fill them in.    The platform maker can leave them blank.  Alternatively, we can remove as many or few of the platofrm fields as we want.

            "POSITIONING_SYSTEM",
                "PTT",
                "TRANS_SYSTEM",
                "PLATFORM_FAMILY",
                "PLATFORM_TYPE",
                "PLATFORM_MAKER",
                "FLOAT_SERIAL_NO",
                "FIRMWARE_VERSION",
                "MANUAL_VERSION",
                "WMO_INST_TYPE",
                "BATTERY_TYPE",
                "CONTROLLER_BOARD_TYPE_PRIMARY",
                "CONTROLLER_BOARD_SERIAL_NO_PRIMARY"

**Comment by SBS-EREHM** [comment]
OK. I've removed PLATFORM/WMO_INST_TYPE as a "required" property
