### ISSUE TITLE
should some more platform fields be 'required'

### ISSUE THREAD

**Issue by BrianKingNOC** [euroargodev/sensor_metadata_json#7]
I can't remember if I've raised this already, but here it is as an 'issue'

There are a few fields which I think are required platform fields, which aren't in the present schema as 'required'

PTT
TRANS_SYSTEM_ID
TRANS_FREQUENCY
CONTROLLER_BOARD_TYPE_SECONDARY
CONTROLLER_BOARD_SERIAL_NO_SECONDARY

Should we require these to be present in all platform json files, even if they are filled with single spaces ?

**Comment by SBS-EREHM** [comment]
Ok, I updated schemas and examples (json_platform, json_floats) with PTT since it is mandatory in section Argo User's Manual 2.4.9.   My approach was to have the JSON Schemas follow the Argo User's Manual - only the **mandatory** metadata name re  **required** in the JSON Schemas.   (See table in Argo User's Manual section 2.4.9, page 59) .

Added as required property
- PTT

Added as _optional_ properties of PLATFORM:
- TRANS_SYSTEM_ID : (Program identifier of the telecommunication subscription. DACs can use N/A or alternative of their choice when not applicable.)
- TRANS_FREQUENCY
- CONTROLLER_BOARD_TYPE/SERIAL_NO_SECONDARY were already available as _optional_ properties.

Aside: We need to check: DACs may be the ones be setting the PTT, TRANS_SYSTEM_ID and TRANS_FREQUENCY, not the manufacturer, but need to check on that.  (That's why I initially left them out.)

(Not sure I actually understand TRANS_FREQUENCY for which the example is 1/44 Hz.  That is obviously NOT the RF transmission frequency.  So, by frequency, do they mean how often does the float retry an unanswered (Iridium) call at the surface?  1/44 is once every 44 seconds?)
